name: ci

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  validate:
    runs-on: ubuntu-latest
    container: cariad/ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pipenv sync --dev

      - name: Validate
        run: pipenv run ./validate.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docker/build-push-action@v2
        with:
          pull: true
